allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - "@next/env@16.2.11"
  - "@next/eslint-plugin-next@16.2.11"
  - "@next/swc-darwin-arm64@16.2.11"
  - "@next/swc-darwin-x64@16.2.11"
  - "@next/swc-linux-arm64-gnu@16.2.11"
  - "@next/swc-linux-arm64-musl@16.2.11"
  - "@next/swc-linux-x64-gnu@16.2.11"
  - "@next/swc-linux-x64-musl@16.2.11"
  - "@next/swc-win32-arm64-msvc@16.2.11"
  - "@next/swc-win32-x64-msvc@16.2.11"
  - eslint-config-next@16.2.11
  - next@16.2.11
  - "@react-pdf/font@4.0.10"
  - "@react-pdf/layout@4.7.1"
  - "@react-pdf/pdfkit@6.0.1"
  - "@react-pdf/render@4.6.1"
  - "@react-pdf/renderer@4.6.1"
  - "@react-pdf/stylesheet@6.2.3"
  - "@react-pdf/textkit@6.4.1"
  - "@react-pdf/types@2.11.3"

overrides:
  postcss@<8.5.10: 8.5.20
  esbuild@<=0.24.2: 0.25.12
  sharp: 0.35.3
