import type { ConfiguratorCatalogue } from "@/domain/configurator/types";

export const terran900RallyConfigurator = {
  modelId: "terran-900-rally",
  modelName: "Terran 900 Rally",
  currency: "RON",
  basePriceMinor: 4_999_000,
  previewAngles: ["front-three-quarter"],
  visualMedia: [
    {
      role: "base",
      image: "/images/models/terran-900-rally-configurator-veridian-v2.webp",
      alt: "VERIDIAN Terran 900 Rally în finisaj Veridian Green",
      viewAngle: "front-three-quarter",
      optionChoiceId: "color-veridian",
      sortOrder: 0,
    },
    {
      role: "base",
      image: "/images/models/terran-900-rally-configurator-glacier-v2.webp",
      alt: "VERIDIAN Terran 900 Rally în finisaj Glacier White",
      viewAngle: "front-three-quarter",
      optionChoiceId: "color-glacier",
      sortOrder: 1,
    },
    {
      role: "base",
      image: "/images/models/terran-900-rally-configurator-ember-v2.webp",
      alt: "VERIDIAN Terran 900 Rally în finisaj Ember Red",
      viewAngle: "front-three-quarter",
      optionChoiceId: "color-ember",
      sortOrder: 2,
    },
  ],
  standardEquipment: [
    "Mânere încălzite",
    "Cruise control",
    "Quickshifter bidirecțional",
    "ABS în viraj",
    "Scut motor aluminium",
    "TFT 7 inch cu navigație",
    "Control tracțiune sensibil la înclinare",
  ],
  groups: [
    {
      id: "finish",
      name: "Culoare și finisaj",
      shortName: "Finisaj",
      description: "Trei finisaje aplicate pe aceeași configurație de bază.",
      mode: "single",
      required: true,
      choices: [
        {
          id: "color-veridian",
          name: "Veridian Green",
          shortDescription: "Metalizat profund, culoarea semnătură VERIDIAN.",
          priceDeltaMinor: 0,
          published: true,
          default: true,
          image:
            "/images/models/terran-900-rally-configurator-veridian-v2.webp",
          swatch: "#007A59",
          badge: "Standard",
        },
        {
          id: "color-glacier",
          name: "Glacier White",
          shortDescription: "Alb perlat cu contrast tehnic graphite.",
          priceDeltaMinor: 79_000,
          published: true,
          image: "/images/models/terran-900-rally-configurator-glacier-v2.webp",
          swatch: "#E8EBE7",
        },
        {
          id: "color-ember",
          name: "Ember Red",
          shortDescription: "Roșu metalizat închis, controlat și sobru.",
          priceDeltaMinor: 79_000,
          published: true,
          image: "/images/models/terran-900-rally-configurator-ember-v2.webp",
          swatch: "#8F1726",
        },
      ],
    },
    {
      id: "ergonomics",
      name: "Șa și ergonomie",
      shortName: "Ergonomie",
      description:
        "Alege înălțimea și sprijinul potrivite stilului tău de drum.",
      mode: "single",
      required: true,
      choices: [
        {
          id: "seat-standard",
          name: "Șa standard 860 mm",
          shortDescription: "Echilibru între control în picioare și confort.",
          priceDeltaMinor: 0,
          published: true,
          default: true,
          badge: "Inclus",
        },
        {
          id: "seat-low",
          name: "Șa joasă 830 mm",
          shortDescription:
            "Acces mai ușor la sol, fără schimbarea suspensiei.",
          priceDeltaMinor: 0,
          published: true,
          excludes: ["passenger-comfort"],
        },
        {
          id: "seat-comfort",
          name: "Șa Comfort 860 mm",
          shortDescription: "Spumă cu densitate dublă pentru etape lungi.",
          priceDeltaMinor: 89_000,
          published: true,
        },
      ],
    },
    {
      id: "technology",
      name: "Tehnologie",
      shortName: "Tehnologie",
      description:
        "Sistemele esențiale sunt incluse; pachetele adaugă capabilități specifice.",
      mode: "single",
      required: true,
      choices: [
        {
          id: "tech-standard",
          name: "VERIDIAN Core",
          shortDescription:
            "Moduri Road și Rain, ABS în viraj și control tracțiune.",
          priceDeltaMinor: 0,
          published: true,
          default: true,
          badge: "Inclus",
        },
        {
          id: "tech-expedition",
          name: "Expedition Tech",
          shortDescription:
            "Monitorizare unghi mort, TPMS și iluminare adaptivă.",
          priceDeltaMinor: 199_000,
          published: true,
        },
        {
          id: "tech-rally",
          name: "Rally Pro",
          shortDescription:
            "Moduri Enduro Pro, reglaje avansate și ABS spate configurabil.",
          priceDeltaMinor: 279_000,
          published: true,
        },
      ],
    },
    {
      id: "protection",
      name: "Protecție",
      shortName: "Protecție",
      description: "Maximum două opțiuni, dimensionate pentru utilizare reală.",
      mode: "multi",
      required: false,
      maxSelections: 2,
      choices: [
        {
          id: "engine-bars",
          name: "Bare protecție motor",
          shortDescription:
            "Structură tubulară graphite, cu puncte de prindere dedicate.",
          priceDeltaMinor: 129_000,
          published: true,
        },
        {
          id: "radiator-guard",
          name: "Protecție radiator",
          shortDescription:
            "Plasă aluminium decupată pentru flux corect de aer.",
          priceDeltaMinor: 49_000,
          published: true,
        },
        {
          id: "rally-protection",
          name: "Kit protecție Rally",
          shortDescription:
            "Extensii laterale și protecții suplimentare pentru carter.",
          priceDeltaMinor: 189_000,
          published: true,
          requires: ["engine-bars"],
          badge: "Necesită bare motor",
        },
      ],
    },
    {
      id: "luggage",
      name: "Bagaje",
      shortName: "Bagaje",
      description: "Sistem modular pentru navetă, weekend sau expediție.",
      mode: "multi",
      required: false,
      maxSelections: 3,
      choices: [
        {
          id: "luggage-rack",
          name: "Cadru modular bagaje",
          shortDescription: "Baza discretă pentru cutii sau genți laterale.",
          priceDeltaMinor: 59_000,
          published: true,
        },
        {
          id: "aluminium-cases",
          name: "Cutii laterale aluminium",
          shortDescription: "Set de 74 L, închidere cu cheia motocicletei.",
          priceDeltaMinor: 329_000,
          published: true,
          requires: ["luggage-rack"],
          excludes: ["soft-bags"],
        },
        {
          id: "soft-bags",
          name: "Genți laterale Adventure",
          shortDescription: "Set flexibil de 50 L, rezistent la apă.",
          priceDeltaMinor: 129_000,
          published: true,
          requires: ["luggage-rack"],
          excludes: ["aluminium-cases"],
        },
        {
          id: "top-case",
          name: "Top case 42 L",
          shortDescription:
            "Spațiu pentru o cască adventure și obiectele zilnice.",
          priceDeltaMinor: 149_000,
          published: true,
          requires: ["luggage-rack"],
        },
      ],
    },
    {
      id: "accessories",
      name: "Accesorii",
      shortName: "Accesorii",
      description: "Detaliile finale pentru confort și navigație.",
      mode: "multi",
      required: false,
      maxSelections: 3,
      choices: [
        {
          id: "passenger-comfort",
          name: "Kit confort pasager",
          shortDescription: "Spătar, mânere și extensie pentru șaua Comfort.",
          priceDeltaMinor: 119_000,
          published: true,
          requires: ["seat-comfort"],
          excludes: ["seat-low", "top-case"],
          badge: "Include șaua Comfort",
        },
        {
          id: "navigation-mount",
          name: "Suport telefon & navigație",
          shortDescription:
            "Montaj amortizat, alimentare USB-C și blocare mecanică.",
          priceDeltaMinor: 39_000,
          published: true,
        },
        {
          id: "tall-screen",
          name: "Parbriz Touring",
          shortDescription: "Cu 55 mm mai înalt, reglabil fără unelte.",
          priceDeltaMinor: 69_000,
          published: true,
        },
        {
          id: "archived-heated-seat",
          name: "Șa încălzită generația 1",
          shortDescription: "Opțiune arhivată, păstrată doar pentru istoric.",
          priceDeltaMinor: 99_000,
          published: false,
        },
      ],
    },
  ],
} as const satisfies ConfiguratorCatalogue;
